/* Build-time only: cc -O2 tools/generate_corridor_sprite_lut.c -o /tmp/ec-lut
 * /tmp/ec-lut > main/corridor_sprite_lut.inc
 * Converts all RGB565 values to the exact nearest designed palette color. */
#include <stdint.h>
#include <stdio.h>
#include "../main/corridor_palette.inc"
int main(void){
    puts("/* Generated by tools/generate_corridor_sprite_lut.c; immutable Flash data. */\nstatic const uint8_t ec_sprite_lut[65536] = {");
    for(unsigned code=0;code<65536;++code){
        int red=((code>>11)&31)*255/31,green=((code>>5)&63)*255/63,blue=(code&31)*255/31;
        unsigned best=0;int error=0x7fffffff;
        for(unsigned i=0;i<256;++i){uint32_t c=ec_palette[i];int dr=red-(int)((c>>16)&255),dg=green-(int)((c>>8)&255),db=blue-(int)(c&255);int e=dr*dr+dg*dg+db*db;if(e<error){error=e;best=i;}}
        printf("%u,%s",best,code%32==31?"\n":"");
    }
    puts("};");return 0;
}
