#!/usr/bin/env python3
"""Bake only the Chinese in-world guide lettering from the OFL Noto font."""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

p = argparse.ArgumentParser()
p.add_argument('--font', required=True)
a = p.parse_args()
image = Image.new('1', (128, 160))
draw = ImageDraw.Draw(image)
font = ImageFont.truetype(a.font, 12)
heading = ImageFont.truetype(a.font, 16)
draw.text((32, 4), '通行须知', font=heading, fill=1)
for text, y in [('请留意通道内的异常', 32), ('发现异常', 55), ('请立即回头', 72), ('没有异常', 95), ('请继续前进', 112), ('从 8 号出口离开', 137)]:
    draw.text((10, y), text, font=font, fill=1)
data = image.tobytes()
lines = ['/* Generated by tools/generate_corridor_notice.py; Noto Sans SC, SIL OFL. */', 'static const uint8_t ec_notice_bits[2560] = {']
lines += [','.join(str(v) for v in data[i:i+32])+',' for i in range(0,len(data),32)]
lines.append('};')
(Path(__file__).resolve().parent.parent/'main/corridor_notice.inc').write_text('\n'.join(lines)+'\n')
