#!/usr/bin/env python3
"""Generate the corridor's bounded indexed palette and lighting lookup tables."""
from pathlib import Path


def generate():
    colors = []
    for i in range(256):
        v = (i % 32) * 255 // 31
        colors.append((i * 255 // 127,) * 3 if i < 128 else
                      (v, v * 84 // 100, v * 28 // 100) if i < 160 else
                      (v, v * 20 // 100, v * 16 // 100) if i < 192 else
                      (v, v * 74 // 100, v * 58 // 100) if i < 224 else
                      (v * 38 // 100, v * 64 // 100, v))
    def nearest(c):
        return min(range(256), key=lambda i: sum((a-b)**2 for a, b in zip(c, colors[i])))
    rows = ['/* Generated by tools/generate_corridor_palette.py; immutable Flash data. */',
            'static const uint32_t ec_palette[256] = {']
    rows += [','.join(f'0xff{r:02x}{g:02x}{b:02x}u' for r, g, b in colors[i:i+8])+',' for i in range(0,256,8)]
    rows.append('};')
    for name, red in [('ec_shade', False), ('ec_red', True)]:
        rows.append(f'static const uint8_t {name}[16][256] = {{')
        for level in range(16):
            values = []
            for rgb in colors:
                r, g, b = [c * (level+1)//16 for c in rgb]
                values.append(nearest((r, g//4, b//4) if red else (r,g,b)))
            rows.append('{'+','.join(map(str, values))+'},')
        rows.append('};')
    return '\n'.join(rows)+'\n'

if __name__ == '__main__':
    (Path(__file__).resolve().parent.parent/'main/corridor_palette.inc').write_text(generate())
